name: "BUILD"
on: workflow_dispatch

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          
      - run: flutter pub get

      - uses: dtolnay/rust-toolchain@stable

      - name: Build ios
        run: |
          flutter build ios --release --no-codesign --verbose

          chmod 777 unbitcode.sh
          sh unbitcode.sh
          
          mkdir -p Payload
          mv ./build/ios/iphoneos/Runner.app Payload
          zip -r -y Payload.zip Payload/Runner.app
          mv Payload.zip BingCopilot.ipa
          
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: BingCopilot.ipa
          path: BingCopilot.ipa
          compression-level: 0

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      
      - run: flutter pub get

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          flutter clean
          flutter build apk --release --split-per-abi --verbose

      # - name: Rename APKs
      #   run: |
      #     mv build/app/outputs/apk/release/app-arm64-v8a-release.apk build/app/outputs/apk/release/BingCopilot-arm64-v8a-release.apk
      #     mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk build/app/outputs/apk/release/BingCopilot-armeabi-v7a-release.apk
      #     mv build/app/outputs/apk/release/app-x86_64-release.apk build/app/outputs/apk/release/BingCopilot-x86_64-release.apk

      - name: Upload APK1
        uses: actions/upload-artifact@v4
        with:
          name: BingCopilot-arm64-v8a-release.apk
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
          compression-level: 0

      - name: Upload APK2
        uses: actions/upload-artifact@v4
        with:
          name: BingCopilot-armeabi-v7a-release.apk
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
          compression-level: 0
      - name: Upload APK3
        uses: actions/upload-artifact@v4
        with:
          name: BingCopilot-x86_64-release.apk
          path: build/app/outputs/apk/release/app-x86_64-release.apk
          compression-level: 0

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          
      - run: flutter pub get

      - uses: dtolnay/rust-toolchain@stable

      - run: flutter build windows --release --verbose

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: BingCopilot-windows-x64.zip
          path: build\windows\x64\runner\Release
          compression-level: 9

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          
      - run: flutter pub get
      - run: sudo apt install libwebkit2gtk-4.1-dev
      - uses: dtolnay/rust-toolchain@stable

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: flutter build linux --release --verbose

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: BingCopilot-linux-x64.zip
          path: build/linux/x64/release/bundle
          compression-level: 9

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      
      - run: flutter pub get

      - uses: dtolnay/rust-toolchain@stable

      - run: flutter build macos --release --verbose
      
      - name: Install tree
        run: brew install tree
        
      - name: Print directory tree
        run: tree build/macos/Build/Products/Release
      
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: BingCopilot-macos-unknown.zip
          path: build/macos/Build/Products/Release/*.app
          compression-level: 9